# Netlify Configuration for Delulu Diaries

# Build settings
[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

# Headers for PWA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# Force HTTPS
[[redirects]]
  from = "http://delulu-diaries.netlify.app/*"
  to = "https://delulu-diaries.netlify.app/:splat"
  status = 301
  force = true
